<?php
/**
 * Roundpad pads storage engine
 *
 * Translations
 *
 * Copyright (C) 2016 PNE Annuaire et Messagerie MEDDE/MLETR
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
$labels['files'] = 'Documents';
$labels['create'] = 'Créer';
$labels['save'] = 'Enregistrer';
$labels['cancel'] = 'Annuler';
$labels['open'] = 'Ouvrir';
$labels['foldercreate'] = 'Nouveau dossier';
$labels['folderedit'] = 'Modification du dossier';
$labels['folderdelete'] = 'Supprimer le dossier';
$labels['folderinside'] = 'Ajouter au dossier';
$labels['foldername'] = 'Nom du dossier';
$labels['filecreate'] = 'Nouveau document';
$labels['filetype'] = 'Type de document';
$labels['folder'] = 'Créer dossier';
$labels['document'] = 'Créer document';
$labels['createfile'] = 'Créer un document';
$labels['name'] = 'Nom';
$labels['created'] = 'Créé le';
$labels['url'] = 'Lien';
$labels['owner'] = 'Propriétaire';
$labels['path'] = 'Chemin';
$labels['mtime'] = 'Modifié';
$labels['type'] = 'Type';
$labels['view'] = 'Ouvrir';
$labels['viewfile'] = 'Ouvrir le document';
$labels['rename'] = 'Renommer le document';
$labels['deletefile'] = 'Supprimer le(s) document(s)';
$labels['edit'] = 'Modifier';
$labels['editfile'] = 'Modifier le document';
$labels['fileedit'] = 'Propriétés du document';
$labels['collection_etherpad'] = 'Tous mes Etherpad';
$labels['collection_ethercalc'] = 'Tous mes Ethercalc';
$labels['foldercreating'] = 'Création d\'un dossier...';
$labels['folderupdating'] = 'Mise à jour d\'un dossier...';
$labels['folderdeleting'] = 'Suppression d\'un dossier...';
$labels['folderdeleteconfirm'] = 'Êtes-vous sûr de de vouloir supprimer le dossier sélectionné ainsi que toutes les données qu\'il contient ?';
$labels['folderdeletenotice'] = 'Le dossier a été supprimé.';
$labels['folderupdatenotice'] = 'Le dossier a été mis à jour.';
$labels['foldercreatenotice'] = 'Le dossier a été créé.';
$labels['fileupdating'] = 'Modification du document...';
$labels['filemoving'] = 'Déplacement de document(s)...';
$labels['filecopying'] = 'Copie de document(s)...';
$labels['filedeleting'] = 'Suppression de document(s)...';
$labels['filedeleteconfirm'] = 'Êtes-vous sûr de de vouloir supprimer les documents sélectionnés ?';
$labels['filedeletenotice'] = 'Le(s) document(s) ont été supprimé(s).';
$labels['filemovenotice'] = 'Le(s) document(s) ont été déplacé(s).';
$labels['filecopynotice'] = 'Le(s) document(s) ont été copié(s).';
$labels['filecreatenotice'] = 'Le document a été créé.';
$labels['allfolders'] = 'Recherche dans tous les dossiers';
$labels['fileskip'] = 'Ignorer';
$labels['fileskipall'] = 'Ignorer tout';
$labels['fileoverwrite'] = 'Écraser';
$labels['fileoverwriteall'] = 'Écraser tout';
$labels['filemoveconfirm'] = 'Cette action va écraser le fichier de destination : <b>$file</b>.';
$labels['getexistingpad'] = 'Enregistrer un document existant';
$labels['padname'] = 'Nom du document';
$labels['fileurl'] = 'Lien vers le document';
$labels['fileowner'] = 'Créateur du document';
$labels['me'] = 'Moi';
$labels['other'] = 'Autre';
$labels['etherpad'] = 'Etherpad';
$labels['ethercalc'] = 'Ethercalc';
$labels['message_subject'] = 'Envoi du document %%file_type%% "%%file_name%%"';
$labels['message_body'] = 'Voici le lien vers le document %%file_type%% "%%file_name%%" : %%file_url%%';
$labels['cantlistfolders'] = 'Impossible de lister les dossiers';
$labels['cantlistfiles'] = 'Impossible de lister les documents';
$labels['cantcreatefile'] = 'Impossible de créer le document';
$labels['cantdeletefiles'] = 'Impossible de supprimer le(s) document(s)';
$labels['cantmovefiles'] = 'Impossible de déplacer le(s) document(s)';
$labels['canteditfile'] = 'Impossible de modifier le document';
$labels['cantcreatefolder'] = 'Impossible de créer le dossier';
$labels['cantdeletefolder'] = 'Impossible de supprimer le dossier';
$labels['cantmovefolder'] = 'Impossible de déplacer le dossier';
$labels['arialabelsearchform'] = 'Zone de recherche des documents';
$labels['arialabelquicksearchbox'] = 'Champ de recherche';
$labels['arialabellistoptions'] = 'Liste d\'options des documents';
$labels['arialabelfolderoptions'] = 'Actions de dossier';
$labels['arialabelfileeditform'] = 'Zone d\'édition de document';
$labels['arialabelfoldercreateform'] = 'Zone de création de document';
$labels['arialabelfoldereditform'] = 'Zone d\'édition de document';
$labels['arialabelfolderlist'] = 'Sélection de dossier';
$labels['arialabelfileselectdialog'] = ' Fenêtre de dialogue de sélection de document.';
$labels['arialabelattachmentoptions'] = 'Options d\'enregistrement des pièces jointes';
$labels['arialabelfilesavedialog'] = 'Boite de dialogue d\'enregistrement de document(s)';
$labels['arialabelfileprops'] = 'Propriétés du document';
$labels['arialabelfilecontent'] = 'Contenu de document';
?>
